# Generated by Django 2.0.4 on 2018-04-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_book_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
